version: '3.6'

volumes:
  eductx-issuer-db:

networks:
  default:
    name: eductx-network

services:
  db:
    image: postgres:15.4-alpine3.18
    container_name: eductx-issuer-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-credentials}
      PGDATA: /data/postgres
    volumes:
      - eductx-issuer-db:/data/postgres
    ports:
      - '127.0.0.1:34569:5432'
    restart: unless-stopped
  # issuer:
  #   image: blockchain-lab-um/eductx-platform-issuer:latest
  #   container_name: eductx-issuer
  #   depends_on:
  #     - db
  #   ports:
  #     - '34568:3001'
  #   environment:
  #     DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-credentials}
  #     PROOF_AUDIENCE: ${PROOF_AUDIENCE}
  #     EBSI_BEARER_TOKEN: ${EBSI_BEARER_TOKEN}
  #     EBSI_PRIVATE_KEY: ${EBSI_PRIVATE_KEY}
  #     EBSI_ID: ${EBSI_ID}
  #     API_KEY: ${API_KEY}
  #     ISSUER_URL: ${ISSUER_URL}
  #   restart: unless-stopped
  # dashboard:
  #   image: blockchain-lab-um/eductx-platform-dashboard:latest
  #   container_name: eductx-dashboard
  #   ports:
  #     - '34567:3000'
  #   environment:
  #     AZURE_AD_CLIENT_ID: ${AZURE_AD_CLIENT_ID}
  #     AZURE_AD_CLIENT_SECRET: ${AZURE_AD_CLIENT_SECRET}
  #     NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
  #     NEXT_PUBLIC_ISSUER_ENDPOINT: 'https://bclabum.informatika.uni-mb.si/eductx-issuer'
  #     NEXT_PUBLIC_APP_URL: 'https://platform2.eductx.org'
  #     API_KEY: ${API_KEY}
  #     BFF_API_KEY: ${BFF_API_KEY}
  #     EMAIL_HOST: mail.um.si
  #     EMAIL_USERNAME: blockchain-lab@um.si
  #     EMAIL_PASSWORD: ${EMAIL_PASSWORD}
  #   restart: unless-stopped
