volumes:
  eductx-issuer-service:
  eductx-authorization-service:

networks:
  default:
    name: eductx-network

services:
  dashboard:
    image: blockchain-lab-um/eductx-platform-dashboard:latest
    container_name: eductx-platform-dashboard
    ports:
      - '34567:3000'
    environment:
      AZURE_AD_CLIENT_ID: ${AZURE_AD_CLIENT_ID}
      AZURE_AD_CLIENT_SECRET: ${AZURE_AD_CLIENT_SECRET}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXT_PUBLIC_ISSUER_ENDPOINT: 'https://bclabum.informatika.uni-mb.si/eductx-issuer'
      NEXT_PUBLIC_APP_URL: 'https://platform2.eductx.org'
      API_KEY: ${API_KEY}
      BFF_API_KEY: ${BFF_API_KEY}
      EMAIL_HOST: mail.um.si
      EMAIL_USERNAME: blockchain-lab@um.si
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    restart: unless-stopped

  issuer-service:
    image: blockchain-lab-um/eductx-platform-issuer-service:latest
    container_name: eductx-platform-issuer-service
    ports:
      - '34568:3001'
    environment:
      VERSION: ${VERSION}
      NETWORK: ${NETWORK}
      KEY_ALG: ${KEY_ALG}
      PRIVATE_KEY: ${PRIVATE_KEY}
      DID_METHOD: ${DID_METHOD}
      EBSI_SUBJECT_ID: ${EBSI_SUBJECT_ID}
      SERVER_URL: ${SERVER_URL}
      AUTHORIZATION_SERVER_URL: ${AUTHORIZATION_SERVER_URL}
      AUTHORIZATION_SERVER_PUBLIC_KEY: ${AUTHORIZATION_SERVER_PUBLIC_KEY}
      AUTHORIZATION_SERVER_KEY_ALG: ${AUTHORIZATION_SERVER_KEY_ALG}
      API_KEY: ${API_KEY}
      CONFORMANCE_TEST_ENABLED: ${CONFORMANCE_TEST_ENABLED}
    restart: unless-stopped
    volumes:
      - eductx-issuer-service:/app/db

  authorization-service:
    image: blockchain-lab-um/eductx-platform-authorization-service:latest
    container_name: eductx-platform-authorization-service
    ports:
      - '34569:3001'
    environment:
      VERSION: ${VERSION}
      NETWORK: ${NETWORK}
      KEY_ALG: ${KEY_ALG}
      PRIVATE_KEY: ${PRIVATE_KEY}
      DID_METHOD: ${DID_METHOD}
      EBSI_SUBJECT_ID: ${EBSI_SUBJECT_ID}
      SERVER_URL: ${SERVER_URL}
      ISSUER_SERVER_URL: ${ISSUER_SERVER_URL}
      ISSUER_SERVER_PUBLIC_KEY: ${ISSUER_SERVER_PUBLIC_KEY}
      ISSUER_SERVER_KEY_ALG: ${ISSUER_SERVER_KEY_ALG}
      CONFORMANCE_TEST_ENABLED: ${CONFORMANCE_TEST_ENABLED}
    restart: unless-stopped
    volumes:
      - eductx-authorization-service:/app/db
