import clsx from 'clsx';

import '../styles/globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, 'flex w-screen justify-center')}>
        <div className="w-full max-w-6xl bg-red-100">{children}</div>
      </body>
    </html>
  );
}
